utils_sources := \
	misc.cpp \
	RefBase.cpp \
	SharedBuffer.cpp \
	Static.cpp \
	String16.cpp \
	String8.cpp \
	SystemClock.cpp \
	Threads.cpp \
	Timers.cpp \
	Unicode.cpp \
	VectorImpl.cpp

objects += $(patsubst %.cpp,utils/%.o, $(utils_sources))